version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: make deps
        - run:
            name: Run linter
            command: make lint
        - run:
            name: Run tests
            command: make test
